name: Create Text File

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run Script
        run: node Scripts/CreateText.js

      - name: Show Output
        run: cat output/hello.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: output/